/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.java.laboratorio11;

import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author codeli4m
 */
public class FormEmpleado extends javax.swing.JFrame {

    
    DefaultTableModel modeloTabla;
    // no puedo declarar un array sin especificar tamano
    List<Empleado> arrayEmpleado = new ArrayList<>();
//    public Empleado[] ArrayEmpleado = new Empleado[4];
    int indexEmpleado = 0;
    /**
     * Creates new form FormEmpleado
     */
    public FormEmpleado() {
        initComponents();
        setupTablaEmpleados();
//        testInsertarDatos();
    }
    
    private void setupTablaEmpleados(){
        String[] nombreColumnas = {"N","Codigo","Nombres","Area","T. Seguro","Horas extras","Sueldo","Monto H.E.","Monto Seguro","Monto Essalud","Sueldo Neto"};
        String[][] datos = {};
        modeloTabla = new DefaultTableModel(datos, nombreColumnas);
        TablaEmpleados.setModel(modeloTabla);
    }

    private void testInsertarDatos(){
//        Object[] filaNueva = { "001","40823","Juan Perez","Sistemas","AFP",1400,3000,40,100,200,2800 };
//        modeloTabla.addRow(filaNueva);
        Empleado emp = new Empleado();
        emp.setArea("Sistem");
        emp.setCodigo("000");
        emp.setHorasExtras(20);
        emp.setNombre("Pepito");
        emp.setSueldoBase(2000);
        emp.setTipoSeguro("AFP");    
        insertarEmpleadoEnTabla(emp);
//        Object[] filaDatosEmpleado = { "0", emp.getCodigo(), emp.getNombre(),emp.getArea(), emp.getTipoSeguro(), emp.getHorasExtras(), emp.getSueldoBase(), montoHorasExtras, montoSeguro, montoEssalud, sueldoNeto };
//        modeloTabla.addRow(filaDatosEmpleado);        
    }
    
    public void insertarEmpleadoEnTabla(Empleado empleado){
        DecimalFormat df2 = new DecimalFormat("####.00");
        String montoHorasExtras = df2.format(empleado.montoHorasExtras());
        String montoSeguro = df2.format(empleado.montoSeguro());
        String montoEssalud = df2.format(empleado.montoEssalud());
        String sueldoNeto = df2.format(empleado.sueldoNeto());
        int numEmpleado = indexEmpleado + 1;
        System.out.println("NUM EMPLEADO: "+numEmpleado);
        Object[] filaDatosEmpleado = { numEmpleado, empleado.getCodigo(), empleado.getNombre(), empleado.getArea(), empleado.getTipoSeguro(), empleado.getHorasExtras(), empleado.getSueldoBase(), montoHorasExtras, montoSeguro, montoEssalud, sueldoNeto };
        modeloTabla.addRow(filaDatosEmpleado);
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        FieldCodigo = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        FieldSueldoBase = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        FieldNombres = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        FieldHorasExtras = new javax.swing.JTextField();
        ComboBoxTipoSeguro = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        ComboBoxArea = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        BotonesContainer = new javax.swing.JPanel();
        jButtonAgregar = new javax.swing.JButton();
        jButtonLimpiar = new javax.swing.JButton();
        jButtonMostrarResumen = new javax.swing.JButton();
        jButtonSalir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TablaEmpleados = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        LabelMayorSueldo = new javax.swing.JLabel();
        LabelMontoHorasExtrasEntre500y800 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        LabelPromedioSueldoNetoMarketing = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        LabelEmpleadoSNPMenorMontoDscto = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        LabelNumeroEmpleadosMontoSeguroMayor100 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        LabelGastoTotalEmpresaPagos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMaximumSize(new java.awt.Dimension(1200, 720));
        setMinimumSize(new java.awt.Dimension(1200, 720));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setMaximumSize(new java.awt.Dimension(1200, 720));
        jPanel1.setMinimumSize(new java.awt.Dimension(1200, 720));
        jPanel1.setPreferredSize(new java.awt.Dimension(1200, 700));

        jLabel1.setBackground(new java.awt.Color(51, 51, 51));
        jLabel1.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("Codigo");

        FieldCodigo.setBackground(new java.awt.Color(204, 204, 204));
        FieldCodigo.setForeground(new java.awt.Color(102, 102, 102));
        FieldCodigo.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        FieldCodigo.setCaretColor(new java.awt.Color(102, 102, 102));
        FieldCodigo.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jLabel2.setBackground(new java.awt.Color(51, 51, 51));
        jLabel2.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 51));
        jLabel2.setText("Sueldo base");

        FieldSueldoBase.setBackground(new java.awt.Color(204, 204, 204));
        FieldSueldoBase.setForeground(new java.awt.Color(102, 102, 102));
        FieldSueldoBase.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        FieldSueldoBase.setCaretColor(new java.awt.Color(102, 102, 102));
        FieldSueldoBase.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jLabel3.setBackground(new java.awt.Color(51, 51, 51));
        jLabel3.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(51, 51, 51));
        jLabel3.setText("Nombres");

        FieldNombres.setBackground(new java.awt.Color(204, 204, 204));
        FieldNombres.setForeground(new java.awt.Color(102, 102, 102));
        FieldNombres.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        FieldNombres.setCaretColor(new java.awt.Color(102, 102, 102));
        FieldNombres.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        jLabel4.setBackground(new java.awt.Color(51, 51, 51));
        jLabel4.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 51, 51));
        jLabel4.setText("Horas Extras");

        FieldHorasExtras.setBackground(new java.awt.Color(204, 204, 204));
        FieldHorasExtras.setForeground(new java.awt.Color(102, 102, 102));
        FieldHorasExtras.setBorder(javax.swing.BorderFactory.createEmptyBorder(2, 8, 2, 8));
        FieldHorasExtras.setCaretColor(new java.awt.Color(102, 102, 102));
        FieldHorasExtras.setDisabledTextColor(new java.awt.Color(153, 153, 153));

        ComboBoxTipoSeguro.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxTipoSeguro.setForeground(new java.awt.Color(102, 102, 102));
        ComboBoxTipoSeguro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "AFP", "SNP" }));

        jLabel5.setBackground(new java.awt.Color(51, 51, 51));
        jLabel5.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Tipo de seguro");

        ComboBoxArea.setBackground(new java.awt.Color(204, 204, 204));
        ComboBoxArea.setForeground(new java.awt.Color(102, 102, 102));
        ComboBoxArea.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Sistemas", "Administracion", "Marketing" }));

        jLabel6.setBackground(new java.awt.Color(51, 51, 51));
        jLabel6.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Area");

        BotonesContainer.setBackground(new java.awt.Color(255, 255, 255));
        BotonesContainer.setLayout(new java.awt.GridLayout(2, 0, 10, 10));

        jButtonAgregar.setBackground(new java.awt.Color(255, 51, 51));
        jButtonAgregar.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jButtonAgregar.setForeground(new java.awt.Color(255, 255, 255));
        jButtonAgregar.setText("Agregar");
        jButtonAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAgregarActionPerformed(evt);
            }
        });
        BotonesContainer.add(jButtonAgregar);

        jButtonLimpiar.setBackground(new java.awt.Color(204, 255, 255));
        jButtonLimpiar.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jButtonLimpiar.setForeground(new java.awt.Color(102, 102, 102));
        jButtonLimpiar.setText("Limpiar");
        BotonesContainer.add(jButtonLimpiar);

        jButtonMostrarResumen.setBackground(new java.awt.Color(0, 51, 255));
        jButtonMostrarResumen.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jButtonMostrarResumen.setForeground(new java.awt.Color(255, 255, 255));
        jButtonMostrarResumen.setText("Mostrar resumen");
        jButtonMostrarResumen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonMostrarResumenActionPerformed(evt);
            }
        });
        BotonesContainer.add(jButtonMostrarResumen);

        jButtonSalir.setBackground(new java.awt.Color(204, 255, 255));
        jButtonSalir.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jButtonSalir.setForeground(new java.awt.Color(102, 102, 102));
        jButtonSalir.setText("Salir");
        BotonesContainer.add(jButtonSalir);

        TablaEmpleados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(TablaEmpleados);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jLabel7.setFont(new java.awt.Font("Liberation Sans", 1, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(51, 51, 51));
        jLabel7.setText("Resumen de datos");

        jLabel8.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(51, 51, 51));
        jLabel8.setText("Nombre del empleado mayor sueldo");

        LabelMayorSueldo.setForeground(new java.awt.Color(51, 51, 51));

        LabelMontoHorasExtrasEntre500y800.setForeground(new java.awt.Color(51, 51, 51));

        jLabel11.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(51, 51, 51));
        jLabel11.setText("Numero empleados MontoHorasExtras (500-800)");

        jLabel12.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(51, 51, 51));
        jLabel12.setText("Promedio sueldo neto Marketing");

        LabelPromedioSueldoNetoMarketing.setForeground(new java.awt.Color(51, 51, 51));

        jLabel14.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(51, 51, 51));
        jLabel14.setText("Empleado SNP con menor monto descuento");

        LabelEmpleadoSNPMenorMontoDscto.setForeground(new java.awt.Color(51, 51, 51));

        jLabel16.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(51, 51, 51));
        jLabel16.setText("Numero de empleados monto seguro mayor a S/. 100 ");

        LabelNumeroEmpleadosMontoSeguroMayor100.setForeground(new java.awt.Color(51, 51, 51));

        jLabel18.setFont(new java.awt.Font("Liberation Sans", 1, 15)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(51, 51, 51));
        jLabel18.setText("Gasto total de la empresa en pagos");

        LabelGastoTotalEmpresaPagos.setForeground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(LabelMontoHorasExtrasEntre500y800, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(LabelMayorSueldo, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jLabel8))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelPromedioSueldoNetoMarketing, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel12)
                    .addComponent(LabelEmpleadoSNPMenorMontoDscto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel14))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(LabelNumeroEmpleadosMontoSeguroMayor100, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel16)
                    .addComponent(LabelGastoTotalEmpresaPagos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel18))
                .addGap(214, 214, 214))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel16)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelNumeroEmpleadosMontoSeguroMayor100, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelMayorSueldo, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel11)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelMontoHorasExtrasEntre500y800, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel18)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(LabelGastoTotalEmpresaPagos, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelPromedioSueldoNetoMarketing, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel14)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(LabelEmpleadoSNPMenorMontoDscto, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 200, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel3))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(ComboBoxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(FieldHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel4))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(ComboBoxArea, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotonesContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 455, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jScrollPane1)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 1139, Short.MAX_VALUE))
                        .addContainerGap(37, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(8, 8, 8)
                                .addComponent(FieldCodigo, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addGap(8, 8, 8)
                                .addComponent(FieldNombres, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(8, 8, 8)
                                .addComponent(ComboBoxTipoSeguro, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel2)
                                .addGap(8, 8, 8)
                                .addComponent(FieldSueldoBase, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel6)
                                .addGap(8, 8, 8)
                                .addComponent(ComboBoxArea, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(8, 8, 8)
                        .addComponent(FieldHorasExtras, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(BotonesContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(30, 30, 30)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 333, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 720, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonMostrarResumenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonMostrarResumenActionPerformed
        double mayorSueldoNeto = 0;
        String nombreEmpMayorSueldoNeto="";
        int numEmpleadosMontoHExtras500_800 = 0;
        double sumSueldoNetoMarketing = 0;
        double SNPMenorMontoDescuento = 999999;
        String nombreEmpSNPMenorMontoDescuento = "";
        int numeroEmpleadosMontoSeguroMayor100 = 0;
        double gastoTotalEmpresa = 0;
        
        int len = arrayEmpleado.size();
        for (int i=0; i<len; i++){
            Empleado emp = arrayEmpleado.get(i);
            if (emp.sueldoNeto() > mayorSueldoNeto){
                mayorSueldoNeto = emp.sueldoNeto();
                nombreEmpMayorSueldoNeto = emp.getNombre();
            }
            
            if (emp.getArea().equalsIgnoreCase("Marketing")){
                sumSueldoNetoMarketing += emp.sueldoNeto();
            }
            
            if (emp.montoSeguro() > 100){
                numeroEmpleadosMontoSeguroMayor100 += 1;
            }
            
            if (500 <= emp.montoHorasExtras()&& emp.montoHorasExtras()<= 800){
                numEmpleadosMontoHExtras500_800 += 1;
            }
            
            if (emp.getTipoSeguro().equalsIgnoreCase("SNP")){
                if (emp.montoSeguro() < SNPMenorMontoDescuento){
                    SNPMenorMontoDescuento = emp.montoSeguro();
                    nombreEmpSNPMenorMontoDescuento = emp.getNombre();
                }
            }
            gastoTotalEmpresa += emp.sueldoNeto();
        }
        DecimalFormat df2 = new DecimalFormat("####.00");
        // mostrar valores en pantalla
        LabelMayorSueldo.setText(nombreEmpMayorSueldoNeto);
        LabelMontoHorasExtrasEntre500y800.setText(String.valueOf(numEmpleadosMontoHExtras500_800));
        double promSueldoNetoMarketing = sumSueldoNetoMarketing/len;
        LabelPromedioSueldoNetoMarketing.setText(df2.format(promSueldoNetoMarketing));
        LabelEmpleadoSNPMenorMontoDscto.setText(nombreEmpSNPMenorMontoDescuento);
        LabelNumeroEmpleadosMontoSeguroMayor100.setText(String.valueOf(numeroEmpleadosMontoSeguroMayor100));
        LabelGastoTotalEmpresaPagos.setText(df2.format(gastoTotalEmpresa));
    }//GEN-LAST:event_jButtonMostrarResumenActionPerformed

    private boolean containOnlyNumbers(String value){
        boolean res = false;
        try {
            String[] chars = value.split("");
            for (String c: chars){
                int _n = Integer.parseInt(c);
            }
            res = true;
        } catch (Exception e) {
            
        }
        return res;
    }

    private boolean isFloat(String value){
        boolean res = false;
        try {
            float _n = Float.parseFloat(value);
            res = true;
        } catch (Exception e) {
        }
        return true;
    }    
    
    private String checkUserInput(String codigo,String nombres,String horasExtras,String sueldoBase){
        if (!containOnlyNumbers(codigo)){
            return "Codigo";
        }
        else if (nombres.length()>= 48){
            return "Nombres";
        }
        else if (!isFloat(horasExtras)){
            return "Horas extras";
        }
        else if (!isFloat(sueldoBase)){
            return "Sueldo base";
        }else{
            return "";
        }
    }
    
    private void jButtonAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAgregarActionPerformed
        Empleado newEmp = new Empleado();
        String nCodigo = FieldCodigo.getText();
        String nHorasExtras = FieldHorasExtras.getText();
        String nNombres = FieldNombres.getText();
        String nSueldoBase = FieldSueldoBase.getText();
        String errorField = checkUserInput(nCodigo, nNombres, nHorasExtras, nSueldoBase);
        if ("".equals(errorField)){
            newEmp.setCodigo(nCodigo);
            newEmp.setNombre(nNombres);            
            newEmp.setHorasExtras(Double.parseDouble(nHorasExtras));
            newEmp.setSueldoBase(Double.parseDouble(nSueldoBase));
            newEmp.setArea(ComboBoxArea.getSelectedItem().toString());
            newEmp.setTipoSeguro(ComboBoxTipoSeguro.getSelectedItem().toString());
            // Agregar objeto al array de Empleados
            arrayEmpleado.add(newEmp);
            insertarEmpleadoEnTabla(newEmp);            
            indexEmpleado++;            
        }
        else{
            String message = "Ocurrio un error en el campo "+errorField;
            JOptionPane.showMessageDialog(null, message);
        }
    }//GEN-LAST:event_jButtonAgregarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormEmpleado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormEmpleado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BotonesContainer;
    private javax.swing.JComboBox<String> ComboBoxArea;
    private javax.swing.JComboBox<String> ComboBoxTipoSeguro;
    private javax.swing.JTextField FieldCodigo;
    private javax.swing.JTextField FieldHorasExtras;
    private javax.swing.JTextField FieldNombres;
    private javax.swing.JTextField FieldSueldoBase;
    private javax.swing.JLabel LabelEmpleadoSNPMenorMontoDscto;
    private javax.swing.JLabel LabelGastoTotalEmpresaPagos;
    private javax.swing.JLabel LabelMayorSueldo;
    private javax.swing.JLabel LabelMontoHorasExtrasEntre500y800;
    private javax.swing.JLabel LabelNumeroEmpleadosMontoSeguroMayor100;
    private javax.swing.JLabel LabelPromedioSueldoNetoMarketing;
    private javax.swing.JTable TablaEmpleados;
    private javax.swing.JButton jButtonAgregar;
    private javax.swing.JButton jButtonLimpiar;
    private javax.swing.JButton jButtonMostrarResumen;
    private javax.swing.JButton jButtonSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
